### ISSUE TITLE
Combined Singularities not registered

### ISSUE THREAD

**Issue by heidrifx** [Wealthyturtle/Eternal-Singularity#4]
After updating to the latest version (1.0.5) the Combined Singularities are not showing up in JEI and all have the same name, Nitronic Singularity, although I'm able to add recipes for them. 
Please fix this issue since it worked just fine in 1.0.4!

**Comment by jthomas17** [comment]
I am wondering if there is any progress on this. I can make recipes for the nitronic singularity but it does not show up in JEI.
